// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVC_vJBpUcmwEgfATNqF1rPKnndAPOq-o',
    appId: '1:956480668898:web:8842ed65ea888dff6f8abb',
    messagingSenderId: '956480668898',
    projectId: 'amberdesign-16679',
    authDomain: 'amberdesign-16679.firebaseapp.com',
    storageBucket: 'amberdesign-16679.firebasestorage.app',
    measurementId: 'G-FKS11MXQDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkhDb-SfdKkBvYmUTQ0tuno3AqMbKvNZk',
    appId: '1:956480668898:android:24b5e7b006e30c876f8abb',
    messagingSenderId: '956480668898',
    projectId: 'amberdesign-16679',
    storageBucket: 'amberdesign-16679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdwhX_Jo187InxCCp6D_4JZlVzReaQRc4',
    appId: '1:956480668898:ios:62fd6354d196afe26f8abb',
    messagingSenderId: '956480668898',
    projectId: 'amberdesign-16679',
    storageBucket: 'amberdesign-16679.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdwhX_Jo187InxCCp6D_4JZlVzReaQRc4',
    appId: '1:956480668898:ios:62fd6354d196afe26f8abb',
    messagingSenderId: '956480668898',
    projectId: 'amberdesign-16679',
    storageBucket: 'amberdesign-16679.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVC_vJBpUcmwEgfATNqF1rPKnndAPOq-o',
    appId: '1:956480668898:web:fc8de2bf9284542e6f8abb',
    messagingSenderId: '956480668898',
    projectId: 'amberdesign-16679',
    authDomain: 'amberdesign-16679.firebaseapp.com',
    storageBucket: 'amberdesign-16679.firebasestorage.app',
    measurementId: 'G-9HXCTGRD8L',
  );
}
